apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-sidecars-configmap
data:
  sidecarconfig.yaml: |
    sidecars:
      - name: cert-installer
        sidecar:
          containers:
            - name: cert-installer
              image: ubuntu
              imagePullPolicy: IfNotPresent
              command: ["sh", "-c", "echo 'hi' > text.txt"]